name: airtable_test
description: End-to-end test for Airtable source using Monke

connector:
  name: Airtable
  type: airtable
  auth_mode: composio
  composio_config:
    account_id: ca_7BqPq2DZVv3C
    auth_config_id: ac_BqB-KxTgOG-J
  config_fields:
    openai_model: "gpt-4.1-mini"  # Model for content generation
    rate_limit_delay_ms: 250  # Delay between API calls (5 rps = 200ms, but being conservative)

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup
    - collection_cleanup

deletion:
  partial_delete_count: 1
  verify_partial_deletion: false  # Airtable source doesn't detect deletions in incremental sync
  verify_remaining_entities: false  # Skip since deletions aren't detected
  verify_complete_deletion: false  # Skip since deletions aren't detected

entity_count: 3  # Number of test records to create

collection:
  name: Airtable Test Collection

verification:
  retry_attempts: 3
  retry_delay_seconds: 5
  score_threshold: 0.0
  expected_fields:
    - Name
    - Description
    - Notes
  # Expected entity types in sync:
  # - AirtableUserEntity (1 per sync)
  # - AirtableBaseEntity (1 per accessible base)
  # - AirtableTableEntity (1 per table created)
  # - AirtableRecordEntity (entity_count records)
  # - AirtableCommentEntity (entity_count comments)
  # - AirtableAttachmentEntity (if records have attachments)
