# Bitbucket connector test configuration
name: "Bitbucket Connector Test"
description: "End-to-end test of Bitbucket connector sync functionality with incremental deletion testing"

connector:
  name: "bitbucket_test"
  type: "bitbucket"
  auth_mode: direct
  auth_fields:
    username: MONKE_BITBUCKET_USERNAME  # Your Atlassian account email
    app_password: MONKE_BITBUCKET_API_TOKEN  # Your API token (used as password)
    workspace: MONKE_BITBUCKET_WORKSPACE
    repo_slug: MONKE_BITBUCKET_REPO_SLUG
  config_fields:
    openai_model: "gpt-4.1-mini"
    branch: "main"
    workspace: "monke-prog"
    repo_slug: "monke-test-repo"
    file_extensions: []

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup

# Entity configuration
entity_count: 3 # Number of entities to create for testing

deletion:
  # Phase 1: Partial deletion
  partial_delete_count: 1 # Number of entities to delete during partial deletion

  # Verification settings
  verify_partial_deletion: true
  verify_remaining_entities: true
  verify_complete_deletion: true

collection:
  name_template: "monke-{connector_type}-test-{timestamp}"
  description: "Test collection for {connector_type} connector"

verification:
  score_threshold: 0.1
  max_retries: 3
  retry_delay_seconds: 5
