name: box_test
description: End-to-end test for Box source

connector:
  name: Box
  type: box

  # ===== HUMAN SETS THIS UP =====
  auth_mode: composio  # Using Composio for authentication
  composio_config:
    account_id: ca_c2JNuBSRZuBp  # Human obtains from Composio
    auth_config_id: ac_5wOUqwXpowSe  # Human obtains from Composio
  # ==============================

  config_fields:
    openai_model: "gpt-4.1-mini"
    max_concurrency: 2

test_flow:
  steps:
    - cleanup              # Clean up any leftover test data
    - create               # Create all entity types (folders, files, comments)
    - sync                 # Trigger Airweave sync
    - verify               # Verify ALL entities appear in Qdrant
    - update               # Update some entities
    - sync                 # Sync again
    - verify               # Verify updates appear
    - partial_delete       # Delete subset of entities
    - sync                 # Sync again
    - verify_partial_deletion  # Verify deletions
    - verify_remaining_entities  # Verify non-deleted entities still exist
    - complete_delete      # Delete all remaining entities
    - sync                 # Final sync
    - verify_complete_deletion  # Verify all gone
    - cleanup              # Final cleanup
    - collection_cleanup   # Delete test collection

deletion:
  partial_delete_count: 2  # Number of entities to delete in partial_delete step
  verify_partial_deletion: true  # Box supports deletion detection
  verify_remaining_entities: true
  verify_complete_deletion: true

entity_count: 3  # Number of folders to create (each gets files and comments)

collection:
  name: Box Test Collection

verification:
  retry_attempts: 5  # Retry verification this many times
  retry_delay_seconds: 10  # Wait between retries
  score_threshold: 0.0  # Minimum similarity score for verification
  expected_fields:  # Fields that should exist on indexed entities
    - name
    - content
    - entity_id
    - created_at
