name: clickup_test
description: End-to-end test for ClickUp source using Monke

connector:
  name: ClickUp
  type: clickup
  auth_mode: composio
  composio_config:
    account_id: ca_TRwRNXWSdR0i
    auth_config_id: ac_Cm8ASKEkutxE
  config_fields:
    openai_model: "gpt-4.1-mini"  # Model for content generation
    rate_limit_delay_ms: 1000  # Increased delay between API calls for ClickUp

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup
    - collection_cleanup

deletion:
  partial_delete_count: 1
  verify_partial_deletion: true
  verify_remaining_entities: true
  verify_complete_deletion: true

entity_count: 3  # Number of main tasks to create (each with subtasks, comments, files)

collection:
  name: ClickUp Test Collection

verification:
  retry_attempts: 3
  retry_delay_seconds: 5
  score_threshold: 0.0
  expected_fields:
    - name
    - description
    - task_id
