name: gitlab_test
description: End-to-end test for GitLab source using Monke

connector:
  name: GitLab
  type: gitlab
  auth_mode: composio
  composio_config:
    account_id: ca_Jf2v3wLSe2ny
    auth_config_id: ac_4Cmt9-UYnWcK
  config_fields:
    openai_model: "gpt-4.1-mini"  # Model for content generation
    max_concurrency: 3  # Parallel entity creation

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup
    - collection_cleanup

deletion:
  partial_delete_count: 1
  verify_partial_deletion: false  # GitLab issues/MRs are closed, not truly deleted
  verify_remaining_entities: false
  verify_complete_deletion: false

entity_count: 2  # Number of each entity type to create (issues, MRs)

collection:
  name: GitLab Test Collection

verification:
  retry_attempts: 5
  retry_delay_seconds: 10
  score_threshold: 0.0
  expected_fields:
    - title
    - description
    - entity_id
