name: sharepoint_test
description: End-to-end test for SharePoint source using Monke

connector:
  name: SharePoint
  type: sharepoint
  auth_mode: composio
  composio_config:
    account_id: ca_eu5m-Swlj1Po
    auth_config_id: ac_nmLSlFUHpA7q
  config_fields:
    openai_model: "gpt-4.1-mini"  # Model for content generation
    rate_limit_delay_ms: 500  # Delay between API calls

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup
    - collection_cleanup

deletion:
  partial_delete_count: 2  # Number of files to delete in partial delete step
  verify_partial_deletion: true  # SharePoint can detect deletions
  verify_remaining_entities: true
  verify_complete_deletion: true

entity_count: 5  # Number of test files to create

collection:
  name: SharePoint Test Collection

verification:
  retry_attempts: 5
  retry_delay_seconds: 10
  score_threshold: 0.0
  expected_fields:
    - name
    - content
    - entity_id
    - created_datetime

# Test-specific configuration
# SharePoint tests will create files in a test folder in the root site's default drive
