name: teams_test
description: End-to-end test for Microsoft Teams source using Monke

connector:
  name: Microsoft Teams
  type: teams
  auth_mode: composio
  composio_config:
    account_id: ca_srD_BIskfuJ0
    auth_config_id: ac_WFotfRU9m25e
  config_fields:
    openai_model: "gpt-4.1-mini"
    max_concurrency: 2

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup
    - collection_cleanup

deletion:
  partial_delete_count: 1
  verify_partial_deletion: false  # Teams message deletion might not be fully supported
  verify_remaining_entities: false
  verify_complete_deletion: false

entity_count: 3

collection:
  name: Microsoft Teams Test Collection

verification:
  retry_attempts: 5
  retry_delay_seconds: 10
  score_threshold: 0.0
  expected_fields:
    - entity_id
    - body_content
