name: zendesk_test
description: End-to-end test for Zendesk source using Monke

connector:
  name: Zendesk
  type: zendesk
  auth_mode: composio
  composio_config:
    account_id: ca_JYKG6s0vkcJ1
    auth_config_id: ac_Ciu4TMkuEY4_
  config_fields:
    # Airweave source config (passed to source connection creation)
    subdomain: "airweavehelp"


    # Bongo-specific config (used for test data generation)
    openai_model: "gpt-4o-mini"  # Model for content generation
    rate_limit_delay_ms: 1000  # Delay between API calls for Zendesk

test_flow:
  steps:
    - cleanup
    - create
    - sync
    - verify
    - update
    - sync
    - verify
    - partial_delete
    - sync
    - verify_partial_deletion
    - verify_remaining_entities
    - complete_delete
    - sync
    - verify_complete_deletion
    - cleanup
    - collection_cleanup

deletion:
  partial_delete_count: 1
  verify_partial_deletion: true
  verify_remaining_entities: true
  verify_complete_deletion: true

entity_count: 3  # Reduced for more reliable testing

collection:
  name: Zendesk Test Collection

verification:
  retry_attempts: 3
  retry_delay_seconds: 5
  score_threshold: 0.0
  expected_fields:
    - subject
    - description
    - id
    - status
