integrations:
  asana:
    auth_type: "oauth2_with_refresh"
    url: "https://app.asana.com/-/oauth_authorize"
    backend_url: "https://app.asana.com/-/oauth_token"
    grant_type: "authorization_code"
    client_id: "1209332365634185"
    client_secret: "asana-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"

  dropbox:
    auth_type: "oauth2_with_refresh"
    url: "https://www.dropbox.com/oauth2/authorize"
    backend_url: "https://api.dropboxapi.com/oauth2/token"
    grant_type: "authorization_code"
    client_id: "6qxkthbgrajkouc"
    client_secret: "dropbox-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    additional_frontend_params:
      token_access_type: "offline"

  gmail:
    auth_type: "oauth2_with_refresh"
    url: "https://accounts.google.com/o/oauth2/auth"
    backend_url: "https://oauth2.googleapis.com/token"
    grant_type: "authorization_code"
    client_id: "502433363466-d8ruvkdb3nkafulj63tnenn8iud31sks.apps.googleusercontent.com"
    client_secret: "gmail-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "https://www.googleapis.com/auth/gmail.readonly"
    additional_frontend_params:
      access_type: "offline"
      prompt: "consent"

  google_calendar:
    auth_type: "oauth2_with_refresh"
    url: "https://accounts.google.com/o/oauth2/auth"
    backend_url: "https://oauth2.googleapis.com/token"
    grant_type: "authorization_code"
    client_id: "818502206676-21n4c60uj6ptrakgboqmfn24rv9jfrln.apps.googleusercontent.com"
    client_secret: "google-calendar-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "https://www.googleapis.com/auth/calendar.events.public.readonly https://www.googleapis.com/auth/calendar.freebusy https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.calendars.readonly https://www.googleapis.com/auth/calendar.events.owned.readonly https://www.googleapis.com/auth/calendar.events.readonly"
    additional_frontend_params:
      access_type: "offline"
      prompt: "consent"

  google_drive:
    auth_type: "oauth2_with_refresh"
    url: "https://accounts.google.com/o/oauth2/auth"
    backend_url: "https://oauth2.googleapis.com/token"
    grant_type: "authorization_code"
    client_id: "308188756994-6pluda2abpu45q91ccg82qve5j69mpk5.apps.googleusercontent.com"
    client_secret: "google-drive-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "https://www.googleapis.com/auth/docs https://www.googleapis.com/auth/drive.photos.readonly https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/drive.metadata https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/gmail.readonly"
    additional_frontend_params:
      access_type: "offline"
      prompt: "consent"

  hubspot:
    auth_type: "oauth2_with_refresh"
    url: "https://app.hubspot.com/oauth/authorize"
    backend_url: "https://api.hubapi.com/oauth/v1/token"
    grant_type: "authorization_code"
    client_id: "4917d5e8-82f8-43ea-9fad-b344b54b33ed"
    client_secret: "hubspot-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "crm.objects.companies.read crm.objects.contacts.read crm.objects.deals.read oauth tickets"

  intercom:
    auth_type: "oauth2"
    url: "https://app.intercom.com/oauth"
    backend_url: "https://api.intercom.io/auth/eagle/token"
    grant_type: "authorization_code"
    client_id: "1f6fa99d-dea8-4b1c-a79b-cf82a1389e4c"
    client_secret: "intercom-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "read write"

  monday:
    auth_type: "oauth2"
    url: "https://auth.monday.com/oauth2/authorize"
    backend_url: "https://auth.monday.com/oauth2/token"
    grant_type: "authorization_code"
    client_id: "ba30562df98324c4e7ea0cd131346c03"
    client_secret: "monday-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "me:read boards:read docs:read workspaces:read users:read account:read updates:read assets:read tags:read teams:read"

  notion:
    auth_type: "oauth2"
    url: "https://api.notion.com/v1/oauth/authorize"
    backend_url: "https://api.notion.com/v1/oauth/token"
    grant_type: "authorization_code"
    client_id: "191d872b-594c-8045-ac77-0037fb8711db"
    client_secret: "notion-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "header"
    additional_frontend_params:
      owner: "user""

  slack:
    auth_type: "oauth2"
    url: "https://slack.com/oauth/v2/authorize"
    backend_url: "https://slack.com/api/oauth.v2.access"
    grant_type: "authorization_code"
    client_id: "6769618979345.8289604264455"
    client_secret: "slack-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "app_mentions:read,channels:history,channels:join,channels:read,groups:history,groups:read,im:history,im:read,mpim:history,mpim:read,users:read"

  stripe:
    auth_type: "api_key"

  todoist:
    auth_type: "oauth2"
    url: "https://todoist.com/oauth/authorize"
    backend_url: "https://todoist.com/oauth/access_token"
    grant_type: "authorization_code"
    client_id: "74e8b22d71a14e51b78e53e7c3e4fbc8"
    client_secret: "todoist-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "data:read"

  trello:
    auth_type: "trello_auth"
    url: "https://trello.com/1/authorize"
    key: "2d051c43173fdbd0e89ac5b71333d310"
    scope: "read"
    callback_method: "fragment"
    expiration: "never"
    name: "Airweave Integration"