integrations:
  asana:
    auth_type: "oauth2_with_refresh"
    url: "https://app.asana.com/-/oauth_authorize"
    backend_url: "https://app.asana.com/-/oauth_token"
    grant_type: "authorization_code"
    client_id: "1208775363497245"
    client_secret_id: "asana-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"

  dropbox:
    auth_type: "oauth2_with_refresh"
    url: "https://www.dropbox.com/oauth2/authorize"
    backend_url: "https://api.dropboxapi.com/oauth2/token"
    grant_type: "authorization_code"
    client_id: "6qxkthbgrajkouc"
    client_secret_keyvault_name: "dropbox-client-secret"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    additional_frontend_params:
      token_access_type: "offline"

  hubspot:
    auth_type: "oauth2_with_refresh"
    url: "https://app.hubspot.com/oauth/authorize"
    backend_url: "https://api.hubapi.com/oauth/v1/token"
    grant_type: "authorization_code"
    client_id: "4917d5e8-82f8-43ea-9fad-b344b54b33ed"
    client_secret: "1c97a378-9d75-4337-947f-bca783f69377"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "body"
    scope: "crm.objects.companies.read crm.objects.contacts.read crm.objects.deals.read oauth tickets"

  notion:
    auth_type: "oauth2_with_refresh"
    url: "https://api.notion.com/v1/oauth/authorize"
    backend_url: "https://api.notion.com/v1/oauth/token"
    grant_type: "authorization_code"
    client_id: "16dd872b-594c-8007-a0ee-00376e9a88a9"
    client_secret: "secret_O3WlZnEMgG8zRX4taqkzoJT5VcDPIos3NVpOdo3YYUl"
    content_type: "application/x-www-form-urlencoded"
    client_credential_location: "header"
    additional_frontend_params:
      owner: "user"