name: Ruff

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/ruff.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/ruff.yml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Git Debug
        run: |
          git status
          git diff
          git rev-parse HEAD
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "ruff==0.1.15"
      - name: Debug Info
        run: |
          which ruff
          ruff --version
          pwd
      - name: Show Exact Differences
        run: |
          ruff format . --check --diff
