name: Ruff

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/**"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/**"
jobs:
  ruff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "ruff>=0.1.14"
      - name: Ruff Check
        run: |
          ruff check .
      - name: Ruff Format Check
        run: |
          ruff format --check .
