name: Backend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: airweave
          POSTGRES_PASSWORD: airweave1234!
          POSTGRES_DB: airweave
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1

      - name: Install dependencies
        run: |
          cd backend
          poetry install

      - name: Run all tests
        env:
          ENCRYPTION_KEY: "SpgLrrEEgJ/7QdhSMSvagL1juEY5eoyCG0tZN7OSQV0=" # This is just a dummy key
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }} # Used for e2e sync tests
          POSTGRES_USER: airweave
          POSTGRES_PASSWORD: airweave1234!
          POSTGRES_DB: airweave
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        run: |
          cd backend
          poetry run pytest tests/
